version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project/basic-spring-boot
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run: 
          command: mvn clean install
          working_directory: ~/project/basic-spring-boot          
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: ~/project/basic-spring-boot/target/surefire-reports
      - store_artifacts:
          path: ~/project/basic-spring-boot/target/testms-0.1.jar