version: 2.1

orbs:
  maven: circleci/maven@1.3.0

workflows:
  maven_test:
    jobs:
      - maven/test: # checkout, build, test, and upload test results
          app_src_directory: basic-spring-boot
          test_results_path: basic-spring-boot/target/surefire-reports