version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: mvn package
          working_directory: ~/project
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: ~/project/target/testms-0.1.jar
      - store_artifacts:
          path: ~/project/target/testms-0.1.jar
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "56:de:3a:2c:69:ca:92:7c:95:55:ee:2c:bb:75:66:bf"
      - run:
          name: Deploy Over SSH
          command: |
            ssh circleci@31.187.75.85 'bash -c cd /home/circleci && \
            mkdir upload_before && \
            kill $(ps aux | grep 'testms-0.1' | awk '{print $2}')  && \
            nohup java -jar testms-0.1.jar > jar-log.log & exit && \
            mkdir upload_after'
#      - run:
#          name: Deploy Over SSH
#          command: |-
#        ssh $SSH_USER@$SSH_HOST 'bash -c CURRDATE=$(date +%s);echo \$CURRDATE; cd /home/circleci && \
#        mkdir test_create_dir'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build

#      - run:
#          name: Deploy Over SSH
#        command: |
#          ssh circleci@31.187.75.85 'bash -c cd /home/circleci && \
#          kill $(ps aux | grep 'testms-0.1' | awk '{print $2}')  && \
#          mkdir upload_before && \
#          nohup java -jar testms-0.1.jar > jar-log.log & exit && \
#          mkdir upload_after'